; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3-waveshare]
monitor_speed = 115200
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = COM5
monitor_port = COM5
board_build.arduino.usb_mode = 1
board_build.arduino.usb_cdc_on_boot = 1
lib_deps = 
	adafruit/Adafruit BNO055
	adafruit/Adafruit Unified Sensor
	asukiaaa/XboxSeriesXControllerESP32_asukiaaa@^1.1.1
	adafruit/Adafruit NeoPixel@^1.15.2
